server:
  port: 8060
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: alfred
    username: alfred
    url: jdbc:postgresql://localhost:5435/payment
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      boostrap: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.alfred.payment.payment.notification.PaymentNotificationRequest