services:
  postgresql:
    container_name: my_postgresql
    image: postgres
    environment:
      POSTGRES_USER: alfred
      POSTGRES_PASSWORD: alfred
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - microservices
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alfred
      - MONGO_INITDB_ROOT_PASSWORD=alfred

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=alfred
      - ME_CONFIG_MONGODB_ADMINPASSWORD=alfred
      - ME_CONFIG_MONGODB_SERVER=mongodb


networks:
  microservices:
    driver: bridge

volumes:
  postgres:
  mongo:
